create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_league_id bigint not null,
  name text not null,
  country_name text,
  gender text,
  tier text,
  logo_url text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_league_id)
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_season_id bigint not null,
  league_id bigint not null references public.leagues(id) on delete cascade,
  name text not null,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  sync_policy text not null default 'incremental',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_season_id),
  unique (league_id, name)
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_team_id bigint not null,
  name text not null,
  short_name text,
  official_name text,
  logo_url text,
  country_name text,
  venue_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_team_id)
);

create table if not exists public.season_teams (
  season_id bigint not null references public.seasons(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (season_id, team_id)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_match_id bigint not null,
  league_id bigint not null references public.leagues(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  round_number integer,
  stage_name text,
  label text,
  kickoff_at timestamptz,
  status text not null default 'scheduled',
  venue_name text,
  home_team_id bigint references public.teams(id) on delete restrict,
  away_team_id bigint references public.teams(id) on delete restrict,
  home_score integer,
  away_score integer,
  home_ht_score integer,
  away_ht_score integer,
  source_updated_at timestamptz,
  last_synced_at timestamptz not null default timezone('utc', now()),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_match_id),
  check (home_team_id is distinct from away_team_id)
);

create table if not exists public.team_match_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  opponent_team_id bigint references public.teams(id) on delete set null,
  venue text not null default 'neutral' check (venue in ('home', 'away', 'neutral')),
  match_status text not null default 'scheduled',
  match_kickoff_at timestamptz not null,
  round_number integer,
  result text not null default 'U' check (result in ('W', 'D', 'L', 'P', 'U')),
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  points integer not null default 0,
  xg_for numeric(12,4),
  xg_against numeric(12,4),
  xp numeric(12,4),
  xt_for numeric(12,4),
  xt_against numeric(12,4),
  shots integer not null default 0,
  shots_on_target integer not null default 0,
  corners integer not null default 0,
  clean_sheet boolean not null default false,
  event_count integer not null default 0,
  source_updated_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (match_id, team_id),
  check (team_id is distinct from opponent_team_id)
);

create table if not exists public.standings (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  snapshot_key text not null default 'current',
  as_of_match_id bigint references public.matches(id) on delete set null,
  as_of_kickoff_at timestamptz,
  matches_played integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  goal_difference integer not null default 0,
  points integer not null default 0,
  xg_for numeric(12,4) not null default 0,
  xg_against numeric(12,4) not null default 0,
  xp numeric(12,4) not null default 0,
  xt_for numeric(12,4) not null default 0,
  xt_against numeric(12,4) not null default 0,
  position integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (season_id, team_id, snapshot_key)
);

create table if not exists public.aggregated_team_stats (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  scope_key text not null,
  snapshot_key text not null default 'current',
  scope_label text not null,
  venue_filter text not null default 'all' check (venue_filter in ('all', 'home', 'away')),
  window_size integer,
  as_of_match_id bigint references public.matches(id) on delete set null,
  as_of_kickoff_at timestamptz,
  matches_in_scope integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  points integer not null default 0,
  points_per_match numeric(12,4) not null default 0,
  form_sequence text[] not null default '{}'::text[],
  avg_goals_for numeric(12,4) not null default 0,
  avg_goals_against numeric(12,4) not null default 0,
  avg_xg_for numeric(12,4) not null default 0,
  avg_xg_against numeric(12,4) not null default 0,
  avg_xp numeric(12,4) not null default 0,
  avg_xt_for numeric(12,4) not null default 0,
  avg_xt_against numeric(12,4) not null default 0,
  clean_sheets integer not null default 0,
  current_position integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (season_id, team_id, scope_key, snapshot_key)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_event_id text not null,
  match_id bigint not null references public.matches(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  opponent_team_id bigint references public.teams(id) on delete set null,
  provider_player_id bigint,
  event_type text,
  event_sub_type text,
  period text,
  minute integer,
  second integer,
  x double precision,
  y double precision,
  end_x double precision,
  end_y double precision,
  xg numeric(12,4),
  xt numeric(12,4),
  is_shot boolean not null default false,
  is_goal boolean not null default false,
  source_updated_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_event_id)
);

create table if not exists public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'wyscout',
  provider_league_id bigint,
  provider_season_ids bigint[] not null default '{}',
  run_kind text not null default 'incremental',
  requested_by text,
  status text not null default 'queued',
  started_at timestamptz,
  finished_at timestamptz,
  matches_scanned integer not null default 0,
  matches_hydrated integer not null default 0,
  matches_upserted integer not null default 0,
  events_upserted integer not null default 0,
  affected_season_ids bigint[] not null default '{}',
  affected_team_ids bigint[] not null default '{}',
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sync_cursors (
  id bigint generated by default as identity primary key,
  provider text not null default 'wyscout',
  provider_league_id bigint not null,
  provider_season_id bigint,
  cursor_key text not null,
  cursor_value text,
  cursor_timestamp timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_league_id, provider_season_id, cursor_key)
);

create index if not exists idx_seasons_league_current
  on public.seasons (league_id, is_current, start_date desc);

create index if not exists idx_season_teams_league_team
  on public.season_teams (league_id, team_id);

create index if not exists idx_matches_season_kickoff
  on public.matches (season_id, kickoff_at desc);

create index if not exists idx_matches_league_kickoff
  on public.matches (league_id, kickoff_at desc);

create index if not exists idx_matches_home_team_kickoff
  on public.matches (home_team_id, kickoff_at desc);

create index if not exists idx_matches_away_team_kickoff
  on public.matches (away_team_id, kickoff_at desc);

create index if not exists idx_team_match_stats_team_scope
  on public.team_match_stats (team_id, season_id, venue, match_kickoff_at desc);

create index if not exists idx_team_match_stats_match
  on public.team_match_stats (match_id);

create index if not exists idx_standings_season_position
  on public.standings (season_id, snapshot_key, position);

create index if not exists idx_aggregated_team_stats_scope
  on public.aggregated_team_stats (season_id, team_id, scope_key, snapshot_key);

create index if not exists idx_events_match_clock
  on public.events (match_id, minute, second);

create index if not exists idx_events_team_type
  on public.events (team_id, season_id, event_type);

create index if not exists idx_sync_runs_status
  on public.sync_runs (status, created_at desc);

create index if not exists idx_sync_cursors_scope
  on public.sync_cursors (provider_league_id, provider_season_id, cursor_key);

drop trigger if exists set_updated_at_on_leagues on public.leagues;
create trigger set_updated_at_on_leagues
before update on public.leagues
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_seasons on public.seasons;
create trigger set_updated_at_on_seasons
before update on public.seasons
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_teams on public.teams;
create trigger set_updated_at_on_teams
before update on public.teams
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_season_teams on public.season_teams;
create trigger set_updated_at_on_season_teams
before update on public.season_teams
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_matches on public.matches;
create trigger set_updated_at_on_matches
before update on public.matches
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_team_match_stats on public.team_match_stats;
create trigger set_updated_at_on_team_match_stats
before update on public.team_match_stats
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_standings on public.standings;
create trigger set_updated_at_on_standings
before update on public.standings
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_aggregated_team_stats on public.aggregated_team_stats;
create trigger set_updated_at_on_aggregated_team_stats
before update on public.aggregated_team_stats
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_events on public.events;
create trigger set_updated_at_on_events
before update on public.events
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_on_sync_cursors on public.sync_cursors;
create trigger set_updated_at_on_sync_cursors
before update on public.sync_cursors
for each row
execute function public.set_updated_at();

create or replace function public.recompute_standings_for_season(
  p_season_id bigint,
  p_snapshot_key text default 'current'
)
returns void
language plpgsql
as $$
begin
  delete from public.standings
  where season_id = p_season_id
    and snapshot_key = p_snapshot_key;

  with registered as (
    select st.season_id, st.league_id, st.team_id
    from public.season_teams st
    where st.season_id = p_season_id
  ),
  completed as (
    select *
    from public.team_match_stats
    where season_id = p_season_id
      and lower(match_status) in ('played', 'complete', 'completed', 'finished', 'match ended')
  ),
  season_latest as (
    select
      p_season_id as season_id,
      max(match_id) as as_of_match_id,
      max(match_kickoff_at) as as_of_kickoff_at
    from completed
  ),
  rolled as (
    select
      registered.season_id,
      registered.league_id,
      registered.team_id,
      count(completed.id)::integer as matches_played,
      coalesce(sum(case when completed.result = 'W' then 1 else 0 end), 0)::integer as wins,
      coalesce(sum(case when completed.result = 'D' then 1 else 0 end), 0)::integer as draws,
      coalesce(sum(case when completed.result = 'L' then 1 else 0 end), 0)::integer as losses,
      coalesce(sum(completed.goals_for), 0)::integer as goals_for,
      coalesce(sum(completed.goals_against), 0)::integer as goals_against,
      coalesce(sum(completed.goals_for - completed.goals_against), 0)::integer as goal_difference,
      coalesce(sum(completed.points), 0)::integer as points,
      coalesce(sum(completed.xg_for), 0)::numeric(12,4) as xg_for,
      coalesce(sum(completed.xg_against), 0)::numeric(12,4) as xg_against,
      coalesce(sum(completed.xp), 0)::numeric(12,4) as xp,
      coalesce(sum(completed.xt_for), 0)::numeric(12,4) as xt_for,
      coalesce(sum(completed.xt_against), 0)::numeric(12,4) as xt_against
    from registered
    left join completed
      on completed.season_id = registered.season_id
     and completed.team_id = registered.team_id
    group by registered.season_id, registered.league_id, registered.team_id
  ),
  positioned as (
    select
      rolled.*,
      dense_rank() over (
        partition by rolled.season_id
        order by
          rolled.points desc,
          rolled.goal_difference desc,
          rolled.goals_for desc,
          rolled.xg_for desc,
          rolled.team_id asc
      )::integer as position
    from rolled
  )
  insert into public.standings (
    season_id,
    league_id,
    team_id,
    snapshot_key,
    as_of_match_id,
    as_of_kickoff_at,
    matches_played,
    wins,
    draws,
    losses,
    goals_for,
    goals_against,
    goal_difference,
    points,
    xg_for,
    xg_against,
    xp,
    xt_for,
    xt_against,
    position,
    metadata
  )
  select
    positioned.season_id,
    positioned.league_id,
    positioned.team_id,
    p_snapshot_key,
    season_latest.as_of_match_id,
    season_latest.as_of_kickoff_at,
    positioned.matches_played,
    positioned.wins,
    positioned.draws,
    positioned.losses,
    positioned.goals_for,
    positioned.goals_against,
    positioned.goal_difference,
    positioned.points,
    positioned.xg_for,
    positioned.xg_against,
    positioned.xp,
    positioned.xt_for,
    positioned.xt_against,
    positioned.position,
    jsonb_build_object(
      'season_id', positioned.season_id,
      'snapshot_key', p_snapshot_key
    )
  from positioned
  cross join season_latest;
end;
$$;

create or replace function public.recompute_aggregated_team_stats(
  p_season_id bigint,
  p_snapshot_key text default 'current'
)
returns void
language plpgsql
as $$
begin
  delete from public.aggregated_team_stats
  where season_id = p_season_id
    and snapshot_key = p_snapshot_key;

  with registered as (
    select st.season_id, st.league_id, st.team_id
    from public.season_teams st
    where st.season_id = p_season_id
  ),
  completed as (
    select *
    from public.team_match_stats
    where season_id = p_season_id
      and lower(match_status) in ('played', 'complete', 'completed', 'finished', 'match ended')
  ),
  ranked as (
    select
      completed.*,
      row_number() over (
        partition by completed.team_id
        order by completed.match_kickoff_at desc, completed.match_id desc
      ) as recent_rank
    from completed
  ),
  latest_per_team as (
    select
      team_id,
      max(match_id) as as_of_match_id,
      max(match_kickoff_at) as as_of_kickoff_at
    from completed
    group by team_id
  ),
  season_full as (
    select
      registered.season_id,
      registered.league_id,
      registered.team_id,
      'season_full'::text as scope_key,
      'Full season'::text as scope_label,
      'all'::text as venue_filter,
      null::integer as window_size,
      count(completed.id)::integer as matches_in_scope,
      coalesce(sum(case when completed.result = 'W' then 1 else 0 end), 0)::integer as wins,
      coalesce(sum(case when completed.result = 'D' then 1 else 0 end), 0)::integer as draws,
      coalesce(sum(case when completed.result = 'L' then 1 else 0 end), 0)::integer as losses,
      coalesce(sum(completed.points), 0)::integer as points,
      coalesce(array_agg(completed.result order by completed.match_kickoff_at desc, completed.match_id desc) filter (where completed.id is not null and completed.result <> 'U'), '{}'::text[]) as form_sequence,
      coalesce(avg(completed.goals_for), 0)::numeric(12,4) as avg_goals_for,
      coalesce(avg(completed.goals_against), 0)::numeric(12,4) as avg_goals_against,
      coalesce(avg(completed.xg_for), 0)::numeric(12,4) as avg_xg_for,
      coalesce(avg(completed.xg_against), 0)::numeric(12,4) as avg_xg_against,
      coalesce(avg(completed.xp), 0)::numeric(12,4) as avg_xp,
      coalesce(avg(completed.xt_for), 0)::numeric(12,4) as avg_xt_for,
      coalesce(avg(completed.xt_against), 0)::numeric(12,4) as avg_xt_against,
      coalesce(sum(case when completed.clean_sheet then 1 else 0 end), 0)::integer as clean_sheets
    from registered
    left join completed
      on completed.season_id = registered.season_id
     and completed.team_id = registered.team_id
    group by registered.season_id, registered.league_id, registered.team_id
  ),
  home_only as (
    select
      registered.season_id,
      registered.league_id,
      registered.team_id,
      'venue_home'::text as scope_key,
      'Home only'::text as scope_label,
      'home'::text as venue_filter,
      null::integer as window_size,
      count(completed.id)::integer as matches_in_scope,
      coalesce(sum(case when completed.result = 'W' then 1 else 0 end), 0)::integer as wins,
      coalesce(sum(case when completed.result = 'D' then 1 else 0 end), 0)::integer as draws,
      coalesce(sum(case when completed.result = 'L' then 1 else 0 end), 0)::integer as losses,
      coalesce(sum(completed.points), 0)::integer as points,
      coalesce(array_agg(completed.result order by completed.match_kickoff_at desc, completed.match_id desc) filter (where completed.id is not null and completed.result <> 'U'), '{}'::text[]) as form_sequence,
      coalesce(avg(completed.goals_for), 0)::numeric(12,4) as avg_goals_for,
      coalesce(avg(completed.goals_against), 0)::numeric(12,4) as avg_goals_against,
      coalesce(avg(completed.xg_for), 0)::numeric(12,4) as avg_xg_for,
      coalesce(avg(completed.xg_against), 0)::numeric(12,4) as avg_xg_against,
      coalesce(avg(completed.xp), 0)::numeric(12,4) as avg_xp,
      coalesce(avg(completed.xt_for), 0)::numeric(12,4) as avg_xt_for,
      coalesce(avg(completed.xt_against), 0)::numeric(12,4) as avg_xt_against,
      coalesce(sum(case when completed.clean_sheet then 1 else 0 end), 0)::integer as clean_sheets
    from registered
    left join completed
      on completed.season_id = registered.season_id
     and completed.team_id = registered.team_id
     and completed.venue = 'home'
    group by registered.season_id, registered.league_id, registered.team_id
  ),
  away_only as (
    select
      registered.season_id,
      registered.league_id,
      registered.team_id,
      'venue_away'::text as scope_key,
      'Away only'::text as scope_label,
      'away'::text as venue_filter,
      null::integer as window_size,
      count(completed.id)::integer as matches_in_scope,
      coalesce(sum(case when completed.result = 'W' then 1 else 0 end), 0)::integer as wins,
      coalesce(sum(case when completed.result = 'D' then 1 else 0 end), 0)::integer as draws,
      coalesce(sum(case when completed.result = 'L' then 1 else 0 end), 0)::integer as losses,
      coalesce(sum(completed.points), 0)::integer as points,
      coalesce(array_agg(completed.result order by completed.match_kickoff_at desc, completed.match_id desc) filter (where completed.id is not null and completed.result <> 'U'), '{}'::text[]) as form_sequence,
      coalesce(avg(completed.goals_for), 0)::numeric(12,4) as avg_goals_for,
      coalesce(avg(completed.goals_against), 0)::numeric(12,4) as avg_goals_against,
      coalesce(avg(completed.xg_for), 0)::numeric(12,4) as avg_xg_for,
      coalesce(avg(completed.xg_against), 0)::numeric(12,4) as avg_xg_against,
      coalesce(avg(completed.xp), 0)::numeric(12,4) as avg_xp,
      coalesce(avg(completed.xt_for), 0)::numeric(12,4) as avg_xt_for,
      coalesce(avg(completed.xt_against), 0)::numeric(12,4) as avg_xt_against,
      coalesce(sum(case when completed.clean_sheet then 1 else 0 end), 0)::integer as clean_sheets
    from registered
    left join completed
      on completed.season_id = registered.season_id
     and completed.team_id = registered.team_id
     and completed.venue = 'away'
    group by registered.season_id, registered.league_id, registered.team_id
  ),
  last_five as (
    select
      registered.season_id,
      registered.league_id,
      registered.team_id,
      'last_5'::text as scope_key,
      'Last 5 matches'::text as scope_label,
      'all'::text as venue_filter,
      5::integer as window_size,
      count(ranked.id)::integer as matches_in_scope,
      coalesce(sum(case when ranked.result = 'W' then 1 else 0 end), 0)::integer as wins,
      coalesce(sum(case when ranked.result = 'D' then 1 else 0 end), 0)::integer as draws,
      coalesce(sum(case when ranked.result = 'L' then 1 else 0 end), 0)::integer as losses,
      coalesce(sum(ranked.points), 0)::integer as points,
      coalesce(array_agg(ranked.result order by ranked.match_kickoff_at desc, ranked.match_id desc) filter (where ranked.id is not null and ranked.result <> 'U'), '{}'::text[]) as form_sequence,
      coalesce(avg(ranked.goals_for), 0)::numeric(12,4) as avg_goals_for,
      coalesce(avg(ranked.goals_against), 0)::numeric(12,4) as avg_goals_against,
      coalesce(avg(ranked.xg_for), 0)::numeric(12,4) as avg_xg_for,
      coalesce(avg(ranked.xg_against), 0)::numeric(12,4) as avg_xg_against,
      coalesce(avg(ranked.xp), 0)::numeric(12,4) as avg_xp,
      coalesce(avg(ranked.xt_for), 0)::numeric(12,4) as avg_xt_for,
      coalesce(avg(ranked.xt_against), 0)::numeric(12,4) as avg_xt_against,
      coalesce(sum(case when ranked.clean_sheet then 1 else 0 end), 0)::integer as clean_sheets
    from registered
    left join ranked
      on ranked.season_id = registered.season_id
     and ranked.team_id = registered.team_id
     and ranked.recent_rank <= 5
    group by registered.season_id, registered.league_id, registered.team_id
  ),
  scopes as (
    select * from season_full
    union all
    select * from home_only
    union all
    select * from away_only
    union all
    select * from last_five
  )
  insert into public.aggregated_team_stats (
    season_id,
    league_id,
    team_id,
    scope_key,
    snapshot_key,
    scope_label,
    venue_filter,
    window_size,
    as_of_match_id,
    as_of_kickoff_at,
    matches_in_scope,
    wins,
    draws,
    losses,
    points,
    points_per_match,
    form_sequence,
    avg_goals_for,
    avg_goals_against,
    avg_xg_for,
    avg_xg_against,
    avg_xp,
    avg_xt_for,
    avg_xt_against,
    clean_sheets,
    current_position,
    metadata
  )
  select
    scopes.season_id,
    scopes.league_id,
    scopes.team_id,
    scopes.scope_key,
    p_snapshot_key,
    scopes.scope_label,
    scopes.venue_filter,
    scopes.window_size,
    latest_per_team.as_of_match_id,
    latest_per_team.as_of_kickoff_at,
    scopes.matches_in_scope,
    scopes.wins,
    scopes.draws,
    scopes.losses,
    scopes.points,
    case
      when scopes.matches_in_scope > 0
        then round(scopes.points::numeric / scopes.matches_in_scope, 4)
      else 0
    end as points_per_match,
    scopes.form_sequence,
    scopes.avg_goals_for,
    scopes.avg_goals_against,
    scopes.avg_xg_for,
    scopes.avg_xg_against,
    scopes.avg_xp,
    scopes.avg_xt_for,
    scopes.avg_xt_against,
    scopes.clean_sheets,
    standings.position,
    jsonb_build_object(
      'season_id', scopes.season_id,
      'scope_key', scopes.scope_key,
      'snapshot_key', p_snapshot_key
    )
  from scopes
  left join latest_per_team
    on latest_per_team.team_id = scopes.team_id
  left join public.standings standings
    on standings.season_id = scopes.season_id
   and standings.team_id = scopes.team_id
   and standings.snapshot_key = p_snapshot_key;
end;
$$;

create or replace function public.refresh_season_derived_data(
  p_season_id bigint,
  p_snapshot_key text default 'current'
)
returns void
language plpgsql
as $$
begin
  perform public.recompute_standings_for_season(p_season_id, p_snapshot_key);
  perform public.recompute_aggregated_team_stats(p_season_id, p_snapshot_key);
end;
$$;